version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:${MC_CONTAINER_VERS}
    container_name: minecraft
    hostname: minecraft
    ports:
      - "${MC_SERVER_PORT}:25565"
      - 8888:8123
    volumes:
      - ./mc:/data
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      TZ: America/Chicago
      VERSION: ${MC_SERVER_VERS}
      MOTD: ${MC_SERVER_MOTD}
      # WHITELIST: ${MC_SERVER_WHITELIST}
      ENABLE_WHITELIST: true
      OVERRIDE_WHITELIST: false
      MEMORY: 16G
      TYPE: spigot
    restart: always
  minecraft-backup:
    image: itzg/mc-backup
    container_name: minecraft-backup-sidecar
    hostname: minecraft-backup-sidecar
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: minecraft
      PRUNE_BACKUPS_DAYS: 2
      # PRE_BACKUP_SCRIPT: |
        # echo "Beginning MC Server backup"
        # rcon-cli --password 1a0a527d7a9355487d8ea14f --host minecraft say "Beginning MC Server backup"
        # echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      EXCLUDES: "*.jar,cache,logs,*.tmp,plugins/dynmap,./plugins/dynmap,./plugins/dynmap/*"
      # POST_BACKUP_SCRIPT_FILE: /data/post-backup.sh
    volumes:
      - ./mc:/data:ro
      - ./mc-backups:/backups